name: CI

on:
  push:
  pull_request:

env:
  VERBOSE: 1

jobs:
  build-test:
    name: Test on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Linux dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get -q -y install check gettext libglib2.0-dev libgtk-3-dev libjson-glib-dev libpango1.0-dev meson ninja-build pkgconf xauth xvfb
    - name: Build and test
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        options: --verbose
