name: CI

on:
  push:
  pull_request:

env:
  VERBOSE: 1

jobs:
  build-test-debian-trixie:
    name: Test on Debian trixie
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pwmt/github-actions-debian:trixie
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          mkdir build
          cd build
          meson ..
          ninja --verbose
          ninja test --verbose
