name: CI

on:
  push:
  pull_request:

env:
  VERBOSE: 1

jobs:
  build-test-debian-trixie:
    name: Test on Debian trixie
    runs-on: ubuntu-latest
    container: ghcr.io/pwmt/github-actions-debian:trixie
    steps:
    - uses: actions/checkout@v4
    - name: Build and test
      - mkdir build
      - cd build
      - meson ..
      - ninja --verbose
      - ninja test --verbose
