name: "IRC Notifications"
on: [push, pull_request, create]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: "#pwmt"
          server: "irc.oftc.net"
          nickname: "gojira2"
          message: |
            [${{github.repository}}] ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: "#pwmt"
          server: "irc.oftc.net"
          nickname: "gojira2"
          message: |
            [${{github.repository}}] ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: "#pwmt"
          server: "irc.oftc.net"
          nickname: "gojira2"
          message: |
            [${{github.repository}}] ${{ github.actor }} tagged ${{ github.event.ref }}
